# Generated by Django 4.1.3 on 2022-12-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_kritiksaran_remove_artikel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritiksaran',
            name='pesan',
            field=models.TextField(),
        ),
    ]
